// src/redux/actionTypes.js
export const SET_AFFILIATE_DATA = 'SET_AFFILIATE_DATA';
export const SET_AFFILIATE_DETAIL_DATA = 'SET_AFFILIATE_DETAIL_DATA';
export const SET_SETTING_DATA = 'SET_SETTING_DATA';


